### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by wavale** [PuppetCrowley/Punkwned-Nuker#1]
LOL NICE GRABBER

**Comment by wavale** [comment]
👍🏽 hehe

**Comment by wavale** [comment]
hey so uh sex?

**Comment by PuppetCrowley** [comment]
> 
> 
> LOL NICE GRABBER

Tell me, where do you can see the regex part or a os.listdir shit? i'm not even using regular expressions XD This is completely open source for some reason, so please, don't be an idiot and learn python.
